### ISSUE TITLE
No module named 'holobot'

### ISSUE THREAD

**Issue by Tavish9** [siddhanthaldar/FISH#1]
### Describe the bug
I am trying to run the fish training. When I launch the program, a compilation error appears.

**Error Messages**

```
Traceback (most recent call last):
  File "train_hand.py", line 19, in <module>
    from replay_buffer_hand import ReplayBufferStorage, make_replay_loader, make_expert_replay_loader, make_ssl_replay_loader
  File "./FISH/FISH/replay_buffer_hand.py", line 13, in <module>
    from holobot.robot.allegro.allegro_kdl import AllegroKDL
ModuleNotFoundError: No module named 'holobot'
```

**Environment(for bug reports)**
- [x] Operating System: Linux version 4.15.0-147-generic (buildd@lcy01-amd64-028) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
- [x] Conda: All environment dependencies are consistent with the provided file `conda_env.yml`

**Steps to Reproduce the Issue**

I followed the instructions in README 

```
conda env create -f conda_env.yml
conda activate fish
python train_hand.py agent=bc suite=hellogym suite/hellogym_task=dooropen num_demos=1
```

I also tried to install using

```
conda install holobot
pip3 install holobot
```

but both of the results show that the package cannot be found.

Would you know how to solve this problem ?

**Comment by varunagrawal** [comment]
It seems like `holobot` is somehow related to the Holo-Dex project and this might be an internal package to the CILVR lab. @siddhanthaldar can you please verify this and let us know what the steps forward are?

**Comment by siddhanthaldar** [comment]
Hi, 

Apologies for the late reply. @varunagrawal is correct that `holobot` was an internal package at the time and had been derived from the [Holo-Dex project](https://github.com/SridharPandian/Holo-Dex). You can follow the instructions there to set it up. 

We recently released an improved teleoperation system, [Open Teach](https://github.com/aadhithya14/Open-Teach/tree/main) which has the VR-based teleop code and all robot controllers public. You might want to take a look since it also supports other robots and has a detailed documentation about setting it up.

Hope that helps!
